#!/usr/bin/env sh

#
# tmuxs - is a simple script to open sessions in myultiple folders. Typically,
# when I turn on the computer I'm always working in a couple projects, thus it
# can be really handy.
#

VERSION=1.0.0

usage() {
	echo -e "Usage: tmuxs [DIRECTORIES]"
	echo -e "Sets a tmux sessions within each directory, and attaches session"
	echo -e "Examples:\n"
	echo -e "tmuxs Desktop -- Opens tmux session in Desktop and attaches it\n"
	echo -e "Report bugs to <cpmachado@protonmail.com>"
	echo -e "or file a issue at https://github.com/cpmachado/bin"
}

version() {
	echo "tmuxs $VERSION"
	echo "Copyright (C) 2019 Carlos Pinto Machado"
	echo "Written by Carlos A. Pinto Machado"
}

ARGV=$@
ARGC=$#

if [ $ARGC -eq 1 ];then
	case $ARGV[0] in
		--version)
			version
			exit
			;;
		*)
			usage
			exit
			;;
	esac
fi

for i in $*;do
	cd $i;
	tmux new -s $(basename $i) -n main -d;
	cd ..;
done

if [ ! $TMUX ]; then
	tmux attach
fi
