#!/usr/bin/env sh

#
# tmuxs - is a simple script to open sessions in myultiple folders. Typically,
# when I turn on the computer I'm always working in a couple projects, thus it
# can be really handy.
#

VERSION=1.0.1

usage() {
	echo "Usage: tmuxs [DIRECTORIES]"
	echo "Sets a tmux sessions within each directory, and attaches session"
	echo "Examples:\n"
	echo "tmuxs Desktop -- Opens tmux session in Desktop and attaches it\n"
	echo "Report bugs to <cpmachado@protonmail.com>"
	echo "or file a issue at https://github.com/cpmachado/bin"
}

version() {
	echo "tmuxs $VERSION"
	echo "Copyright (C) 2019 Carlos Pinto Machado"
	echo "Written by Carlos A. Pinto Machado"
}


case $1 in
	--version)
		version
		exit
		;;
	--help)
		usage
		exit
		;;
	*)
		break
		;;
esac

for i in $*;do
	cd $i;
	tmux new -s $(basename $i) -n main -d;
	cd ..;
done

if [ ! $TMUX ]; then
	tmux attach
fi
