#!/usr/bin/env sh

#
# wrap is a devolved nohup that simply ignores everything. Many a times, for
# GUI applications I care little about. For example, while opening a pdf in a
# gnome machine. 'wrap evince doc1.pdf doc2.pdf'
#

VERSION=1.0.1

usage() {
	echo "Usage: wrap command args"
	echo "Wraps a command to disregard stdout and stderr"
	echo "Examples:\n"
	echo "wrap firefox -- Opens firefox and ignores stdout and stderr\n"
	echo "Report bugs to <cpmachado@protonmail.com>"
	echo "or file a issue at https://github.com/cpmachado/bin"
}

version() {
	echo "wrap $VERSION"
	echo "Copyright (C) 2019 Carlos Pinto Machado"
	echo "Written by Carlos A. Pinto Machado"
}


case $1 in
	--version)
		version
		exit
		;;
	--help)
		usage
		exit
		;;
	*)
		break
		;;
esac

if [ -z $# ];then
	usage
	exit
fi

$* >/dev/null 2>&1 &


